[package]
name = "cve-match-keyword"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
futures = "0.3.30"
log = "0.4.20"
rayon = "1.8.0"
regex = "1.10.2"
serde = "1.0.193"
serde_json = "1.0.108"
tokio-uring = { version = "0.4.0", features = ["bytes"] }
